---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::010438472260:role/pcc-monitoring-QagwAMNU-backend-role
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  local-config.yaml: |
       auth_enabled: false
       
       server:
         http_listen_port: 3100
         grpc_listen_port: 9096
       
       common:
         instance_addr: 0.0.0.0
         path_prefix: /tmp/loki
         replication_factor: 1
         ring:
           kvstore:
             store: inmemory
       
       query_range:
         results_cache:
           cache:
             embedded_cache:
               enabled: true
               max_size_mb: 100
       
       schema_config:
         configs:
           - from: 2020-10-24
             store: tsdb
             object_store: s3
             schema: v13
             index:
               prefix: index_
               period: 24h
       
       storage_config:
         tsdb_shipper:
           active_index_directory: /tmp/loki/index
           cache_location: /tmp/loki/cache
         aws:
           s3: s3://ap-southeast-2
           bucketnames: pcc-monitoring-qagwamnu-bucket
       
       limits_config:
         max_query_lookback: 672h
         retention_period: 672h
       
       compactor:
         working_directory: /tmp/loki/compactor
         compaction_interval: 5m
         delete_request_store: s3
         retention_enabled: true
       
       ruler:
         alertmanager_url: http://localhost:9093

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  type: ClusterIP
  ports:
  - name: loki-http
    protocol: TCP
    port: 3100
  - name: loki-grpc
    protocol: TCP
    port: 9096
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: backend
      containers:
        - name: loki
          image: grafana/loki:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
              name: http-loki
              protocol: TCP
            - containerPort: 9096
              name: grpc-loki
              protocol: TCP
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
---
