---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  type: ClusterIP
  ports:
  - name: loki-http
    protocol: TCP
    port: 3100
  - name: loki-grpc
    protocol: TCP
    port: 9096
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: backend
      containers:
        - name: loki
          image: grafana/loki:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
              name: http-loki
              protocol: TCP
            - containerPort: 9096
              name: grpc-loki
              protocol: TCP
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
---
