apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app4-pcc-secrets
  namespace: monitoring
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: App4PCC
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
          - path: bearer_token
            objectAlias: bearer_token
  secretObjects:
    - secretName: App4PCC
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: bearer_token
          key: bearer_token
